name: Build Artifact and Deploy

on:
  push:
    branches:
      - dev

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  AZURE_WEBAPP_NAME: my-app-name  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'           # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      run: echo "Using Node.js ${{ env.NODE_VERSION }}"
        
    - name: npm install, build, and test
      run: echo "npm install, build, and test"
    
    - name: Zip artifact for deployment
      run: echo "Zip artifact for deployment"

    - name: Upload artifact for deployment job
      run: echo "Upload artifact for deployment job"

  deployDev:
    name: Deploy to Dev
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${{ steps.deploy-to-webapp-dev.outputs.run }}

    steps:
      - name: Download artifact from build job
        run: echo "Download artifact from build job"

      - name: unzip artifact for deployment
        run: echo "unzip artifact for deployment"

      - name: "Deploy to Azure Dev WebApp"
        id: deploy-to-webapp-dev
        run: echo "Deploy to Azure Dev WebApp"
  
  
  deployProd:
    name: Deploy to Production
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: deployDev
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp-prd.outputs.run }}

    steps:
      - name: Download artifact from build job
        run: echo "Download artifact from build job"

      - name: unzip artifact for deployment
        run: echo "unzip artifact for deployment"

      - name: "Deploy to Azure Dev WebApp"
        id: deploy-to-webapp-prd
        run: echo "Deploy to Azure Dev WebApp"
  