name: main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  Sonnar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "Teste"

  Dependecy-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "Teste"

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "Teste"
    
    needs: [Sonnar, Dependecy-Check]

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "Teste"
    
    needs: [Test]

  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "Teste"
    
    needs: [Build]
  
