name: workflow-main

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  workflow-app:
    uses: lucianobeja79/workflows-config/.github/workflows/workflow-app.yml@main
    with:
      name: 'workflow-app'

