name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 
      run: echo "Using Node.js"
        
    - name: npm install, build, and test
      run: echo "npm install, build, and test"
    
    - name: Zip artifact for deployment
      run: echo "Zip artifact for deployment"

    - name: Upload artifact for deployment job
      run: echo "Upload artifact for deployment job"
