name: Build Artifact and Deploy

on:
  push:
    branches:
      - dev

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  AZURE_WEBAPP_NAME: my-app-name # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'          # set this to the node version to use

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml

  build:
    needs: ci
    name: Build
    uses: ./.github/workflows/build.yaml

  deploy-dev:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target: [Development, Perfornance, Quality]
    uses: ./.github/workflows/deployment.yaml
    with:
      target-env: ${{ matrix.target }}
    secrets: inherit

  functional-test:
      needs: deploy-dev
      name: Functional Tests
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Test Functional
        run: echo "Test Functional"

  deploy-prd:
    needs: functional-test
    strategy:
      fail-fast: true
      matrix:
        target: [Production]
    uses: ./.github/workflows/deployment.yaml
    with:
      target-env: ${{ matrix.target }}
    secrets: inherit
      